In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import rcParams
from matplotlib.cm import rainbow

import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
dataset = pd.read_csv('data1.csv')

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1950 entries, 0 to 1949
Data columns (total 21 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   A1      1950 non-null   int64 
 1   A2      1950 non-null   int64 
 2   A3      1950 non-null   int64 
 3   A4      1950 non-null   int64 
 4   A5      1950 non-null   int64 
 5   A6      1950 non-null   int64 
 6   A7      1950 non-null   int64 
 7   A8      1950 non-null   int64 
 8   A9      1950 non-null   int64 
 9   A10     1950 non-null   int64 
 10  A11     1950 non-null   int64 
 11  A12     1950 non-null   int64 
 12  A13     1950 non-null   int64 
 13  A14     1950 non-null   int64 
 14  A15     1950 non-null   int64 
 15  A16     1950 non-null   int64 
 16  A17     1950 non-null   int64 
 17  A18     1950 non-null   int64 
 18  A19     1950 non-null   int64 
 19  A20     1950 non-null   int64 
 20  Class   1950 non-null   object
dtypes: int64(20), object(1)
memory usage: 320.1+ KB


In [4]:
dataset

A1   A2   A3   A4   A5   A6   A7   A8   A9  A10  ...  A12  A13  A14  \
0      54  175  120  175  175    3  175  175  120  175  ...  175  120  175   
1     175  120  175  175  175    7    3    3  175  120  ...    7  175    7   
2     175    3  120  175  175  120  175  120  120  175  ...   54  140    3   
3     175  174    7  175    7  119    3    3  175    3  ...  175  120  175   
4     175   54    7  174    3  175  120    7  175  175  ...  175  175    3   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1945  168  102  168  102  265  168  265  168  168  168  ...  168  265  265   
1946  168  168  168  168  102  265  168  265  265  265  ...  168  168  168   
1947  265  168  168  265  265  168  168  168  168  168  ...  265  168  168   
1948  102  168  265  168  265  265  168  168  168  168  ...  265  168  168   
1949  168  168  265  168  168  265  168  168  168  168  ...  168  168  168   

      A15  A16  A17  A18  A19  A20    Class  
0     175  120  175    3    3    3   Normal  
1     119  174   54    3    3  175   Normal  
2     175  120  175  175  175  175   Normal  
3       7  175    3  175  120  175   Normal  
4     175  120  175    3    3  120   Normal  
...   ...  ...  ...  ...  ...  ...      ...  
1945  168  265  265  265  168  265  Anomaly  
1946  168  265  168  168  102  265  Anomaly  
1947  265  265  168  168  168  168  Anomaly  
1948  168  102  168  265  168  265  Anomaly  
1949  168  168  168  168  168  168  Anomaly  

[1950 rows x 21 columns]

In [5]:
dataset=dataset.replace(to_replace='?',value='0')

In [6]:
print('Finding missing values')
print(dataset.isnull().sum())

Finding missing values
A1       0
A2       0
A3       0
A4       0
A5       0
A6       0
A7       0
A8       0
A9       0
A10      0
A11      0
A12      0
A13      0
A14      0
A15      0
A16      0
A17      0
A18      0
A19      0
A20      0
Class    0
dtype: int64


In [7]:
#dataset['id']=dataset['id'].dataset(dataset['id'].mean())

In [8]:
#print('Finding missing values')
#print(dataset.isnull().sum())

In [9]:
#dataset = dataset.dropna()
#dataset

In [10]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
dataset['Class']= labelencoder_X.fit_transform(dataset['Class'])

In [11]:
dataset

A1   A2   A3   A4   A5   A6   A7   A8   A9  A10  ...  A12  A13  A14  \
0      54  175  120  175  175    3  175  175  120  175  ...  175  120  175   
1     175  120  175  175  175    7    3    3  175  120  ...    7  175    7   
2     175    3  120  175  175  120  175  120  120  175  ...   54  140    3   
3     175  174    7  175    7  119    3    3  175    3  ...  175  120  175   
4     175   54    7  174    3  175  120    7  175  175  ...  175  175    3   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1945  168  102  168  102  265  168  265  168  168  168  ...  168  265  265   
1946  168  168  168  168  102  265  168  265  265  265  ...  168  168  168   
1947  265  168  168  265  265  168  168  168  168  168  ...  265  168  168   
1948  102  168  265  168  265  265  168  168  168  168  ...  265  168  168   
1949  168  168  265  168  168  265  168  168  168  168  ...  168  168  168   

      A15  A16  A17  A18  A19  A20  Class  
0     175  120  175    3    3    3      1  
1     119  174   54    3    3  175      1  
2     175  120  175  175  175  175      1  
3       7  175    3  175  120  175      1  
4     175  120  175    3    3  120      1  
...   ...  ...  ...  ...  ...  ...    ...  
1945  168  265  265  265  168  265      0  
1946  168  265  168  168  102  265      0  
1947  265  265  168  168  168  168      0  
1948  168  102  168  265  168  265      0  
1949  168  168  168  168  168  168      0  

[1950 rows x 21 columns]

In [12]:
y = dataset['Class']
X = dataset.drop(['Class'], axis = 1)
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X = sc_X.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [13]:
gnb = GaussianNB()

In [14]:
#Train the model using the training sets
gnb.fit(X_train, y_train)

GaussianNB()

In [15]:
#Predict the response for test dataset
y_pred = gnb.predict(X_test)
for i in range(0, len(y_pred)):
    i2=str(i)
    res=''
    if y_pred[i]==0:
        res='normal'
    elif y_pred[i]==1:
        res='Anomaly'
    print('Test data ',i2 , ' is ',res)

Test data  0  is  Anomaly
Test data  1  is  normal
Test data  2  is  normal
Test data  3  is  normal
Test data  4  is  normal
Test data  5  is  normal
Test data  6  is  Anomaly
Test data  7  is  normal
Test data  8  is  normal
Test data  9  is  normal
Test data  10  is  normal
Test data  11  is  normal
Test data  12  is  normal
Test data  13  is  Anomaly
Test data  14  is  normal
Test data  15  is  Anomaly
Test data  16  is  Anomaly
Test data  17  is  Anomaly
Test data  18  is  Anomaly
Test data  19  is  Anomaly
Test data  20  is  Anomaly
Test data  21  is  normal
Test data  22  is  normal
Test data  23  is  normal
Test data  24  is  Anomaly
Test data  25  is  normal
Test data  26  is  normal
Test data  27  is  normal
Test data  28  is  normal
Test data  29  is  Anomaly
Test data  30  is  Anomaly
Test data  31  is  normal
Test data  32  is  Anomaly
Test data  33  is  normal
Test data  34  is  Anomaly
Test data  35  is  normal
Test data  36  is  Anomaly
Test data  37  is  normal
Test da

In [16]:
print(confusion_matrix(y_test,y_pred))

[[134  93]
 [104 157]]


In [17]:
from sklearn import metrics
print("Accuracy for Naive Bayes Classifier : {}%".format(metrics.accuracy_score(y_test, y_pred)*100))

Accuracy for Naive Bayes Classifier : 59.63114754098361%


In [18]:
from sklearn.svm import SVC

In [19]:
svclassifier = SVC()
svclassifier.fit(X_train, y_train)

SVC()

In [20]:
y_pred = svclassifier.predict(X_test)
for i in range(0, len(y_pred)):
    i2=str(i)
    res=''
    if y_pred[i]==0:
        res='normal'
    elif y_pred[i]==1:
        res='Anomaly'
    print('Test data ',i2 , ' is ',res)

Test data  0  is  Anomaly
Test data  1  is  normal
Test data  2  is  Anomaly
Test data  3  is  Anomaly
Test data  4  is  normal
Test data  5  is  Anomaly
Test data  6  is  normal
Test data  7  is  Anomaly
Test data  8  is  normal
Test data  9  is  Anomaly
Test data  10  is  Anomaly
Test data  11  is  normal
Test data  12  is  normal
Test data  13  is  normal
Test data  14  is  normal
Test data  15  is  Anomaly
Test data  16  is  normal
Test data  17  is  Anomaly
Test data  18  is  Anomaly
Test data  19  is  Anomaly
Test data  20  is  Anomaly
Test data  21  is  normal
Test data  22  is  normal
Test data  23  is  normal
Test data  24  is  Anomaly
Test data  25  is  Anomaly
Test data  26  is  normal
Test data  27  is  Anomaly
Test data  28  is  normal
Test data  29  is  normal
Test data  30  is  Anomaly
Test data  31  is  normal
Test data  32  is  Anomaly
Test data  33  is  Anomaly
Test data  34  is  Anomaly
Test data  35  is  Anomaly
Test data  36  is  normal
Test data  37  is  normal
Te

In [21]:
print(confusion_matrix(y_test,y_pred))
#print(classification_report(y_test,y_pred))

[[207  20]
 [ 14 247]]


In [22]:
print("Accuracy for SVM Classifier : {}%".format(metrics.accuracy_score(y_test, y_pred)*100))

Accuracy for SVM Classifier : 93.0327868852459%


In [28]:
from sklearn.neighbors import KNeighborsClassifier

In [29]:
knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [30]:
y_pred = knn.predict(X_test)
for i in range(0, len(y_pred)):
    i2=str(i)
    res=''
    if y_pred[i]==0:
        res='normal'
    elif y_pred[i]==1:
        res='Anomaly'
    print('Test data ',i2 , ' is ',res)

Test data  0  is  Anomaly
Test data  1  is  normal
Test data  2  is  normal
Test data  3  is  Anomaly
Test data  4  is  normal
Test data  5  is  normal
Test data  6  is  normal
Test data  7  is  normal
Test data  8  is  normal
Test data  9  is  normal
Test data  10  is  Anomaly
Test data  11  is  normal
Test data  12  is  normal
Test data  13  is  Anomaly
Test data  14  is  normal
Test data  15  is  Anomaly
Test data  16  is  normal
Test data  17  is  Anomaly
Test data  18  is  normal
Test data  19  is  Anomaly
Test data  20  is  Anomaly
Test data  21  is  normal
Test data  22  is  normal
Test data  23  is  normal
Test data  24  is  normal
Test data  25  is  Anomaly
Test data  26  is  normal
Test data  27  is  Anomaly
Test data  28  is  normal
Test data  29  is  normal
Test data  30  is  Anomaly
Test data  31  is  normal
Test data  32  is  Anomaly
Test data  33  is  normal
Test data  34  is  Anomaly
Test data  35  is  Anomaly
Test data  36  is  Anomaly
Test data  37  is  normal
Test da

In [31]:
print(confusion_matrix(y_test,y_pred))

[[182  45]
 [ 83 178]]


In [32]:
print("Accuracy for KNN Classifier : {}%".format(metrics.accuracy_score(y_test, y_pred)*100))

Accuracy for KNN Classifier : 73.77049180327869%


In [33]:
SGD = GradientBoostingClassifier(learning_rate=0.1)
SGD.fit(X_train, y_train)

GradientBoostingClassifier()

In [34]:
y_pred = SGD.predict(X_test)
for i in range(0, len(y_pred)):
    i2=str(i)
    res=''
    if y_pred[i]==0:
        res='normal'
    elif y_pred[i]==1:
        res='Anomaly'
    print('Test data ',i2 , ' is ',res)

Test data  0  is  Anomaly
Test data  1  is  normal
Test data  2  is  Anomaly
Test data  3  is  Anomaly
Test data  4  is  normal
Test data  5  is  Anomaly
Test data  6  is  normal
Test data  7  is  Anomaly
Test data  8  is  normal
Test data  9  is  Anomaly
Test data  10  is  Anomaly
Test data  11  is  normal
Test data  12  is  normal
Test data  13  is  normal
Test data  14  is  normal
Test data  15  is  Anomaly
Test data  16  is  normal
Test data  17  is  Anomaly
Test data  18  is  Anomaly
Test data  19  is  Anomaly
Test data  20  is  Anomaly
Test data  21  is  normal
Test data  22  is  normal
Test data  23  is  normal
Test data  24  is  Anomaly
Test data  25  is  Anomaly
Test data  26  is  normal
Test data  27  is  Anomaly
Test data  28  is  normal
Test data  29  is  normal
Test data  30  is  Anomaly
Test data  31  is  normal
Test data  32  is  Anomaly
Test data  33  is  Anomaly
Test data  34  is  Anomaly
Test data  35  is  Anomaly
Test data  36  is  normal
Test data  37  is  normal
Te

In [35]:
print(confusion_matrix(y_test,y_pred))

[[210  17]
 [ 11 250]]


In [36]:
print("Accuracy for SGD Classifier : {}%".format(metrics.accuracy_score(y_test, y_pred)*100))

Accuracy for SGD Classifier : 94.26229508196722%


In [37]:
from sklearn.ensemble import VotingClassifier
#rf=RandomForestClassifier(n_estimators=40,oob_score=True)
#rf1=GradientBoostingClassifier(learning_rate=0.1)
#rf2 = KNeighborsClassifier(n_neighbors=7)
clf = BaggingClassifier(n_estimators = 40, random_state = 22)
#gnb = GaussianNB()
estimators = []
estimators.append(('clf', clf))
#estimators.append(('rf', rf))
#estimators.append(('rf1', rf1))
#estimators.append(('rf2', rf2))
#estimators.append(('gnb', gnb))
ensemble = VotingClassifier(estimators)

from sklearn.ensemble import VotingClassifier
rf=RandomForestClassifier(n_estimators=40,oob_score=True)
clf = BaggingClassifier(n_estimators = 40, random_state = 22)
estimators = []
estimators.append(('clf', clf))
estimators.append(('rf', rf))
ensemble = VotingClassifier(estimators)

In [38]:
ensemble.fit(X_train, y_train)

VotingClassifier(estimators=[('clf',
                              BaggingClassifier(n_estimators=40,
                                                random_state=22))])

In [39]:
y_pred = ensemble.predict(X_test)
for i in range(0, len(y_pred)):
    i2=str(i)
    res=''
    if y_pred[i]==0:
        res='normal'
    elif y_pred[i]==1:
        res='Anomaly'
    print('Test data ',i2 , ' is ',res)

Test data  0  is  Anomaly
Test data  1  is  normal
Test data  2  is  Anomaly
Test data  3  is  Anomaly
Test data  4  is  normal
Test data  5  is  Anomaly
Test data  6  is  normal
Test data  7  is  Anomaly
Test data  8  is  normal
Test data  9  is  Anomaly
Test data  10  is  Anomaly
Test data  11  is  normal
Test data  12  is  Anomaly
Test data  13  is  normal
Test data  14  is  normal
Test data  15  is  Anomaly
Test data  16  is  normal
Test data  17  is  Anomaly
Test data  18  is  Anomaly
Test data  19  is  Anomaly
Test data  20  is  Anomaly
Test data  21  is  normal
Test data  22  is  normal
Test data  23  is  normal
Test data  24  is  Anomaly
Test data  25  is  Anomaly
Test data  26  is  Anomaly
Test data  27  is  Anomaly
Test data  28  is  normal
Test data  29  is  normal
Test data  30  is  Anomaly
Test data  31  is  normal
Test data  32  is  Anomaly
Test data  33  is  Anomaly
Test data  34  is  Anomaly
Test data  35  is  Anomaly
Test data  36  is  normal
Test data  37  is  normal


In [40]:
print(confusion_matrix(y_test,y_pred))

[[222   5]
 [  3 258]]


In [41]:
print("Accuracy for Ensemble Tree Classifier : {}%".format(metrics.accuracy_score(y_test, y_pred)*100))

Accuracy for Ensemble Tree Classifier : 98.36065573770492%
